ANDROID: lib/crypto: fix build failures for crypto modules
KernelCI is reporting the following build failures when overridable
crypto lib functions are built as modules.

with gcc-14:
ERROR: modpost: "fips140_lib_funcs" [lib/crypto/libaes.ko] undefined!
ERROR: modpost: "fips140_lib_funcs_loaded" [lib/crypto/libaes.ko] undefined!
ERROR: modpost: "fips140_lib_funcs" [lib/crypto/libsha512.ko] undefined!
ERROR: modpost: "fips140_lib_funcs_loaded" [lib/crypto/libsha512.ko] undefined!

with clang-21:
ERROR: modpost: "fips140_lib_funcs_loaded" [lib/crypto/libaes.ko] undefined!
ERROR: modpost: "fips140_lib_funcs" [lib/crypto/libaes.ko] undefined!
ERROR: modpost: "fips140_lib_funcs_loaded" [lib/crypto/libsha512.ko] undefined!
ERROR: modpost: "fips140_lib_funcs" [lib/crypto/libsha512.ko] undefined!

Prevent these by exporting the relevant symbols.

Fixes: 1aa0ebd06571 ("ANDROID: lib/crypto: Support overriding crypto library functions")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:e416fb9310dd6c21ba87e5a579823499869a5b28
Closes: https://d.kernelci.org/i/maestro:9a30d464241350a75a57ab8ac2a0bd161113db29
Change-Id: Iab156a59ab5b2b535343c3cadd08f812444e3fbf
Signed-off-by: Tiffany Yang <ynaffit@google.com>