ANDROID: kleaf: Add 3 more GPU related symbols to _DB845C_MODULE_OUTS
Solve the following pre-submit test failure:

  ERROR: The following kernel modules are built but not copied.
    Add these lines to the module_outs attribute of @//common:db845c_no_kgdb:
      "drivers/gpu/drm/bridge/aux-hpd-bridge.ko",
      "drivers/gpu/drm/bridge/aux-bridge.ko",
      "drivers/gpu/drm/drm_exec.ko",

Fixes: e560518a6c2e ("drm/bridge: implement generic DP HPD bridge")
Fixes: 2a04739139b2 ("drm/bridge: add transparent bridge helper")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I0ba9f4133f723cd739372da38bf7ea05a22e140b