ANDROID: fix kernelci build-break in fair.c
Fix an issue for non-GKI builds found by the 0-day test bot:

kernel/sched/fair.c: In function 'select_task_rq_fair':
>> kernel/sched/fair.c:6766:6: error: implicit declaration of function
	'trace_android_rvh_select_task_rq_fair_enabled';
	did you mean 'trace_android_rvh_select_task_rq_fair'?
    6766 |  if (trace_android_rvh_select_task_rq_fair_enabled())
         |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         |      trace_android_rvh_select_task_rq_fair
   cc1: some warnings being treated as errors

Reported-by: kernel test robot <lkp@intel.com>
Fixes: c7ba09ce6aa5 ("ANDROID: sched/fair: Sync task util for strf hook")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I1b15b9ada83dc5b2678cef3910a7aedc0d19f174