ANDROID: gki_defconfig: Disable MEDIA_SUPPORT_FILTER
We got some undefined API errors. The APIs we need (CONFIG_VIDEO_DEV)
depends on !CONFIG_MEDIA_SUPPORT_FILTER and CONFIG_MEDIA_SUPPORT_FILTER
is set to y by the commit 4467f1150461c2c0760496ec5d33c2381fe5e932
("ANDROID: gki_defconfig: Enable MEDIA_SUPPORT_FILTER").

To solve the error, disable MEDIA_SUPPORT_FILTER and CONFIG_VIDEO_DEV
will be set.

ERROR: modpost: "video_ioctl2" undefined!
ERROR: modpost: "video_devdata" undefined!
ERROR: modpost: "v4l2_device_unregister" undefined!
ERROR: modpost: "video_unregister_device" undefined!
ERROR: modpost: "__video_register_device" undefined!
ERROR: modpost: "video_device_release_empty" undefined!
ERROR: modpost: "v4l2_device_register" undefined!

Bug: 163582226
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Change-Id: Ib22c542db67eaef00c021dd2fa701754f4861890