ANDROID: debug_kinfo: Replace strlcpy() with compatible and safer variant strscpy()
strlcpy() has now been formally removed from the kernel due to the risks it poses.

Fixes the following build error:

  drivers/android/debug_kinfo.c:161:2: error:
    call to undeclared library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)';
      ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    161 |         strlcpy(info->last_uts_release, init_utsname()->release, sizeof(info->last_uts_release));
        |         ^

Fixes: d26270061ae6 ("string: Remove strlcpy()")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ib2b863c07676495626dd03af762ddb201d326127