ANDROID: PM: sleep: Guard device_pm_callback exports with CONFIG_PM_SLEEP
Commit e68849097e82f ("PM: tracing: Hide device_pm_callback events under
PM_SLEEP") wrapped the TRACE_EVENT definitions for device_pm_callback_start
and device_pm_callback_end in include/trace/events/power.h under
CONFIG_PM_SLEEP to avoid defining unused 5KB trace events. However, the
corresponding EXPORT_TRACEPOINT_SYMBOL_GPL calls in power-traces.c were
not similarly guarded, resulting in build errors when CONFIG_PM_SLEEP is
disabled:

  error: '__tracepoint_device_pm_callback_start' undeclared here

Guard the exports with the same CONFIG_PM_SLEEP check.

Bug: 158528747
Change-Id: I134fb008e91712dcb2c388d0192c19ba2f64c21c
Signed-off-by: Vineeth Pillai <vineethrp@google.com>