Revert "ANDROID: GKI: Convert L2TP as modules"
This reverts commit 7070a0ef92d64a9f7ccd51f6688bd9935c3a543e.

Reason for revert: Breaks the platform build as looks like android-base.config has this set to =y and build checks for it to be =y.

To resolve these errors:

ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
For kernel requirements at matrix level 8, For config CONFIG_L2TP, value = m but required y
: Success
INCOMPATIBLE

Change-Id: I5a489401eb71027318792381258ca14ce2111415
Signed-off-by: Ramji Jiyani <ramjiyani@google.com>