ANDROID: abi: update symbol list for desktop
In order to enable the module hid-sensor-prox, we need to add some
symbols.

Fixes the following build errors:
ERROR: modpost: "hid_set_field" [drivers/hid/hid-sensor-hub.ko] undefined!
ERROR: modpost: "hid_hw_request" [drivers/hid/hid-sensor-hub.ko] undefined!
ERROR: modpost: "int_pow" [drivers/iio/common/hid-sensors/hid-sensor-iio-common.ko] undefined!
ERROR: modpost: "__iio_device_register" [drivers/iio/light/hid-sensor-prox.ko] undefined!
ERROR: modpost: "iio_device_unregister" [drivers/iio/light/hid-sensor-prox.ko] undefined!

5 function symbol(s) added
  'int __iio_device_register(struct iio_dev*, struct module*)'
  'void hid_hw_request(struct hid_device*, struct hid_report*, enum hid_class_request)'
  'int hid_set_field(struct hid_field*, unsigned int, __s32)'
  'void iio_device_unregister(struct iio_dev*)'
  'u64 int_pow(u64, unsigned int)'

Bug: 442414507
Test: tools/bazel run \
//private/devices/google/x86-64/intel/brya:brya_dist --config=brya

Change-Id: I3775d4cbc77554c8cd7197aa3797f459438b6ffa
Signed-off-by: Ricardo Ribalda <ribalda@google.com>
Bypass-Upstream-Divergence-Tracking