ANDROID: 16K: x86/vdso: Fix 32-bit vdso layout
The number of PAGE_SIZE pages per VDSO page is being calculated
inconsistently for 32-bit x86 builds. VDSO_NR_PAGES is scaled by 1 but
VDSO_NR_VCLOCK_PAGES is scaled by 4, causing the following kernelci
build errors:

with clang-21:
arch/x86/entry/vdso/vma.c:30:15: error: static assertion failed due to requirement 'VDSO_NR_PAGES + (2 * (((1UL) << 14) / ((1UL) << 12))) == (6 * (((1UL) << 14) / ((1UL) << 12)))': VDSO_NR_PAGES + VDSO_NR_VCLOCK_PAGES == __VDSO_PAGES
   30 | static_assert(VDSO_NR_PAGES + VDSO_NR_VCLOCK_PAGES == __VDSO_PAGES);
      | ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:77:50: note: expanded from macro 'static_assert'
   77 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
      |                                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:78:56: note: expanded from macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
arch/x86/entry/vdso/vma.c:30:52: note: expression evaluates to '12 == 24'
   30 | static_assert(VDSO_NR_PAGES + VDSO_NR_VCLOCK_PAGES == __VDSO_PAGES);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
./include/linux/build_bug.h:77:50: note: expanded from macro 'static_assert'
   77 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
      |                                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:78:56: note: expanded from macro '__static_assert'
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                                        ^~~~
1 error generated.

with gcc-14:
./include/linux/build_bug.h:78:41: error: static assertion failed: "VDSO_NR_PAGES + VDSO_NR_VCLOCK_PAGES == __VDSO_PAGES"
   78 | #define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
      |                                         ^~~~~~~~~~~~~~
./include/linux/build_bug.h:77:34: note: in expansion of macro ‘__static_assert’
   77 | #define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
      |                                  ^~~~~~~~~~~~~~~
arch/x86/entry/vdso/vma.c:30:1: note: in expansion of macro ‘static_assert’
   30 | static_assert(VDSO_NR_PAGES + VDSO_NR_VCLOCK_PAGES == __VDSO_PAGES);
      | ^~~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:291: arch/x86/entry/vdso/vma.o] Error 1
make[4]: *** [scripts/Makefile.build:553: arch/x86/entry/vdso] Error 2
make[3]: *** [scripts/Makefile.build:553: arch/x86/entry] Error 2
make[2]: *** [scripts/Makefile.build:553: arch/x86] Error 2

Add guards around the 32-bit x86 definition to fix this.

Fixes: 4840288585a9 ("ANDROID: 16K: Align vDSO mappings to 16K on x86")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:d083d5a315bc25e917f10d938dc277968265a6f1
Closes: https://d.kernelci.org/i/maestro:241b6404e5584a5470836a5fe2f24db868973146
Change-Id: I3404785c79fde2698233c37a9b7e620a52713479
Signed-off-by: Tiffany Yang <ynaffit@google.com>