Update patch set 3
Patch Set 3:

This change broke the build in kernelci:

kernelci: https://kernelci.org/build/android/branch/android-4.4/kernel/ASB-2018-04-05_4.4-4-g71b3c043fe2d/

../drivers/platform/goldfish/pdev_bus.c: In function 'goldfish_new_pdev':
../drivers/platform/goldfish/pdev_bus.c:133:2: error: implicit declaration of function 'gf_write_ptr' [-Werror=implicit-function-declaration]
  gf_write_ptr(name, pdev_bus_base + PDEV_BUS_GET_NAME,
  ^
cc1: some warnings being treated as errors
../scripts/Makefile.build:277: recipe for target 'drivers/platform/goldfish/pdev_bus.o' failed
make[4]: *** [drivers/platform/goldfish/pdev_bus.o] Error 1
../drivers/platform/goldfish/goldfish_pipe_v2.c: In function 'transfer_max_buffers':
../drivers/platform/goldfish/goldfish_pipe_v2.c:366:1: warning: the frame size of 2848 bytes is larger than 2048 bytes [-Wframe-larger-than=]
 }
 ^

Patch-set: 3
CC: Gerrit User 1069543 <1069543@85c56323-6fa9-3386-8a01-6480fb634889>