ANDROID: 16K: perf: ring_buffer: Fix unused variable
Fix the following kernelci build breakages by removing an unnecessary
variable initialization in 'rb_free_work'.:

with gcc-14:
kernel/events/ring_buffer.c: In function ‘rb_free_work’:
kernel/events/ring_buffer.c:932:13: error: unused variable ‘metadata_pages’ [-Werror=unused-variable]
  932 |         int metadata_pages = __PAGE_SIZE / PAGE_SIZE;
      |             ^~~~~~~~~~~~~~
  CC      kernel/events/callchain.o
cc1: all warnings being treated as errors
make[4]: *** [scripts/Makefile.build:291: kernel/events/ring_buffer.o]
Error 1

with clang-21:
kernel/events/ring_buffer.c:932:6: error: unused variable 'metadata_pages' [-Werror,-Wunused-variable]
  932 |         int metadata_pages = __PAGE_SIZE / PAGE_SIZE;
      |             ^~~~~~~~~~~~~~
1 error generated.
make[4]: *** [scripts/Makefile.build:291: kernel/events/ring_buffer.o] Error 1
make[3]: *** [scripts/Makefile.build:548: kernel/events] Error 2

Fixes: aff2eb701946 ("ANDROID: 16K: perf: ring_buffer: Use __PAGE_SIZE for metadata")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:67687c4d0d733aff6a3a038a2726e6b6b3423d90
Closes:https://d.kernelci.org/i/maestro:34c0f0f339fb9b7bd77cfb32d5f799ead2c43213
Closes: https://d.kernelci.org/i/maestro:578751cc9840ca52640ac9356f8d0822a20e2500
Change-Id: Iedcd17c6530b1d834bcf7551fcd5c17fb42423c5
Signed-off-by: Tiffany Yang <ynaffit@google.com>