ANDROID: userfaultfd: do not untag user pointers from userfaultfd_continue
The patch merged into aosp kernel is different from the one on upstream.
This patch was to fix the following build breakage

./common/fs/userfaultfd.c:1875:32: error: incompatible pointer to integer conversion passing '__u64 *' (aka 'unsigned long long *') to parameter of type '__u64' (aka 'unsigned long long'); remove & [-Werror,-Wint-conversion]

        ret = validate_range(ctx->mm, &uffdio_continue.range.start,
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./common/fs/userfaultfd.c:1245:14: note: passing argument to parameter 'start' here
                                          __u64 start, __u64 len)
                                                ^
  CC      drivers/usb/class/cdc-acm.o
  AR      drivers/net/ethernet/ni/built-in.a
1 error generated.

Bug: 195268596
Change-Id: I7ad40df213897314c439480f22a2ef4712e84025
Signed-off-by: Aaron Ding <aaronding@google.com>
Fixes: ac329b33e94f ("Merge 5.10.54 into android13-5.10")