earlycon: Fix compile error when SERIAL_CORE is m
When set CONFIG_SERIAL_EARLYCON=y and CONFIG_SERIAL_CORE=m, there is
a compile error as below:

  ld: vmlinux.o: in function `parse_options.constprop.0':
  earlycon.c:(.init.text+0xba5a3): undefined reference to `uart_parse_earlycon'

Since the SERIAL_EARLYCON use 'uart_parse_earlycon' which defined in
SERIAL_CORE, so should select rather than depends on.

Fixes: 9aac5887595b ("tty/serial: add generic serial earlycon")
Signed-off-by: Zhang Xiaoxu <zhangxiaoxu5@huawei.com>
Signed-off-by: Alessio Balsini <balsini@google.com>

Change-Id: I903d71d8a8ca2dd64ff71baf4e020b58b92bebfe