Update patch set 4
Patch Set 4:

> Patch Set 3:
> 
> To keep things working we also need a follow on patch to enable PINCTRL_MSM=m for db845c_gki.fragment.
> 
> Additionally, just these patches fail to build with:
> ERROR: Differences between ksymtab and whitelist detected!
> Symbols missing from ksymtab:
>  - msm_pinctrl_dev_pm_ops
>  - msm_pinctrl_probe
>  - msm_pinctrl_remove
> 
> So we need an ABI update as well (I had to update db845c list and drop those values from the qcom list as well).

I have updated the ABI snapshot over weekend and there was conflicts. I have re uploaded the changes on latest tip of android-5.4-stable. Please let me know if I need to merge the ABI snapshot gerrit with any other gerrit to let the automation merge. 


-Thanks, Prasad

Patch-set: 4