Update patch set 3
Patch Set 3:

To keep things working we also need a follow on patch to enable PINCTRL_MSM=m for db845c_gki.fragment.

Additionally, just these patches fail to build with:
ERROR: Differences between ksymtab and whitelist detected!
Symbols missing from ksymtab:
 - msm_pinctrl_dev_pm_ops
 - msm_pinctrl_probe
 - msm_pinctrl_remove

So we need an ABI update as well (I had to update db845c list and drop those values from the qcom list as well).

Patch-set: 3