ANDROID: vendor_hooks: Add vh_folios_put_direct_free
I added a vendor hook "vh_folios_put_refs_direct_free_extent" in 'commit
afdc0cbbc106 ("ANDROID: vendor_hooks: Add vh_folios_put_refs_direct_free_extent")',
while the hook name is too long and causes a build error when used:

ERROR: modpost: too long symbol "__tracepoint_android_vh_folios_put_refs_direct_free_extent".

The root cause is that in `scripts/mod/modpost.c`, exported symbol names
are checked against `MODULE_NAME_LEN`.

Since vendor hooks cannot be renamed, I submitted a new vendor hook at the
same call site.

Bug: 504935225
Change-Id: Ic9bc72066790df04633ef82e7eec483bd0d10bc0
Signed-off-by: Wenchao Hao <haowenchao@xiaomi.corp-partner.google.com>