ANDROID: Fix !CONFIG_SMP build issue with some of the proxy-exec logic
Maciej Żenczykowski reported seeing build failures with configs
using CONFIG_SMP=n

kernel/sched/core.c: In function ‘find_proxy_task’:
kernel/sched/core.c:7476:18: error: implicit declaration of function ‘is_cpu_allowed’; did you mean ‘cpuset_cpus_allowed’? [-Wimplicit-function-d
eclaration]
 7476 |         WARN_ON(!is_cpu_allowed(p, p->wake_cpu));
      |                  ^~~~~~~~~~~~~~
./include/asm-generic/bug.h:123:32: note: in definition of macro ‘WARN_ON’
  123 |         int __ret_warn_on = !!(condition);                              \
      |                                ^~~~~~~~~
kernel/sched/core.c:7476:39: error: ‘struct task_struct’ has no member named ‘wake_cpu’; did you mean ‘wake_q’?
 7476 |         WARN_ON(!is_cpu_allowed(p, p->wake_cpu));
      |                                       ^~~~~~~~

Obviously the logic in find_proxy_task trying to check if return
migration is needed is unnecessary on UP. So lets ifdef it out
as a quick and somewhat ugly solution.

Reported-by: Maciej Żenczykowski <maze@google.com>
Fixes: e4239ea599c6 ("ANDROID: sched: Handle blocked-waiter migration (and return migration)")
Change-Id: Iee6424745004431589530dddeb92627efe581b78
Signed-off-by: John Stultz <jstultz@google.com>