Create patch set 6
Change has been successfully rebased and submitted as 6a2c5a9c6e782c7df9fffd31d67be62e41b4f00b

4 is the latest approved patch-set.
No files were changed between the latest approved patch-set and the submitted one.


Patch-set: 6
Patch-set-description: Rebase
Subject: FROMGIT: mm: huge_mm: fix undefined reference to `mthp_stats' for CONFIG_SYSFS=n
Status: merged
Commit: 6a2c5a9c6e782c7df9fffd31d67be62e41b4f00b
Tag: autogenerated:gerrit:merged
Groups: 6148f0d6cde1ad0d8b1e7f78e7182a90865c9dfe
Label: Code-Review=+2, 7d7a640178e4b32d59d9234aec9fde70414bc9fb Gerrit User 1157738 <1157738@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=+2, 1ab7aedae5872a6dfde890c86121e063e744e6cc Gerrit User 1930620 <1930620@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Lint=+1, 9798576b1ba862c102a71849ab9c1eb1c8195932 Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Performance=+2, ba93728fa74c7da29a5c882cc70952425646f454 Gerrit User 2052902 <2052902@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Verified-Together=+1, d55c51e3353458159991b3656dcfe3593eaf9fe2 Gerrit User 2025861 <2025861@85c56323-6fa9-3386-8a01-6480fb634889>
Label: SUBM=+1, 010c01895b34c4a96272b1ecab15658b928f20b9
Submission-id: 3132672
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Build-Team-Review
Submitted-with: MAY: Code-Review: Gerrit User 1930620 <1930620@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Open-Source-Licensing
Submitted-with: MAY: Lint: Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: API-Review
Submitted-with: MAY: NDK-API-Review
Submitted-with: MAY: AIDL-API-Review
Submitted-with: MAY: Global-Approval
Submitted-with: MAY: Exempt
Submitted-with: MAY: Performance: Gerrit User 2052902 <2052902@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Autosubmit
Submitted-with: MAY: Presubmit-Ready
Submitted-with: MAY: Presubmit-Verified
Submitted-with: MAY: Bypass-Presubmit
Submitted-with: MAY: Presubmit-Verified-Together: Gerrit User 2025861 <2025861@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Build-Cop-Override
Submitted-with: MAY: DrNo-Review
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1743590 \u003c1743590@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 2052564 \u003c2052564@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1499410 \u003c1499410@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}