ANDROID: abi_gki_aarch64_qcom: Update symbol list
CONFIG_USB_EHSET_TEST_FIXTURE enables ehset misc class driver
which is needed for running USB IF electrical compliance. Below
is seen compilation error when enabling this config to compile
as module:

MODPOST modules-only.symvers
ERROR: modpost: "usb_control_msg_recv" [drivers/usb/misc/ehset.ko] undefined!
ERROR: modpost: "usb_control_msg_send" [drivers/usb/misc/ehset.ko] undefined

Fix above compilation with add required symbols.
Leaf changes summary: 2 artifacts changed
Changed leaf types summary: 0 leaf type changed
Removed/Changed/Added functions summary: 0 Removed, 0 Changed,
2 Added functions
Removed/Changed/Added variables summary: 0 Removed, 0 Changed,
0 Added variable

2 Added functions:
[A] 'function int usb_control_msg_recv(usb_device*, __u8, __u8,
__u8, __u16, __u16, void*, __u16, int, gfp_t)'
[A] 'function int usb_control_msg_send(usb_device*, __u8, __u8,
__u8, __u16, __u16, void*, __u16, int, gfp_t)'

Bug: 232128297
Change-Id: If15df15fc3f315447b53fe04b56f70267afd14c0
Signed-off-by: Mayank Rana <quic_mrana@quicinc.com>