ANDROID: x86/process: Fix kernelci build break from implicit declaration
There's a call to 'stack_trace_save_tsk()' in x86/process.c that is
causing the following build errors.

When compiled with clang-21:
arch/x86/kernel/process.c:979:2: error: implicit declaration of function 'stack_trace_save_tsk' [-Werror,-Wimplicit-function-declaration]
  979 |         stack_trace_save_tsk(p, &entry, 1, 0);
      |         ^
1 error generated.

With gcc-14:
arch/x86/kernel/process.c: In function ‘get_wchan’:
arch/x86/kernel/process.c:979:9: error: implicit declaration of function ‘stack_trace_save_tsk’ [-Werror=implicit-function-declaration]
  979 |         stack_trace_save_tsk(p, &entry, 1, 0);
      |         ^~~~~~~~~~~~~~~~~~~~

Prevent this by guarding the call with the appropriate #ifdef.

Fixes: a7137fe7042d ("Revert "x86: Fix __get_wchan() for !STACKTRACE"")
Change-Id: I2f54bc5f218ac562f89a47032c5307b93617d0ae
Signed-off-by: Tiffany Yang <ynaffit@google.com>