Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: I3f157a84ae1bf2301a2e785728899df005d40d5b
Subject: FROMGIT: mm: huge_mm: fix undefined reference to `mthp_stats' for CONFIG_SYSFS=n
Branch: refs/heads/android15-6.6
Status: new
Topic: 
Commit: a54ae98daa09e9f6602e2e76a45b0a10fc8f5617
Tag: autogenerated:gerrit:newPatchSet
Groups: 8ae61a6ff193ba5ef33845691685f673fefab28c
Reviewer: Gerrit User 1157738 <1157738@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1743590 <1743590@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 2052564 <2052564@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1930620 <1930620@85c56323-6fa9-3386-8a01-6480fb634889>
Private: false
Work-in-progress: false
Attention: {"person_ident":"Gerrit User 1743590 \u003c1743590@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 1157738 \u003c1157738@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 2052564 \u003c2052564@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"ADD","reason":"Reviewer was added"}
Attention: {"person_ident":"Gerrit User 1930620 \u003c1930620@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"ADD","reason":"Reviewer was added"}