ANDROID: GKI: fdt: export symbols required by modules
Export symbol for modulized drivers.

ERROR: "of_fdt_get_ddrrank" [techpack/video/msm/msm-vidc.ko] undefined!
ERROR: "of_fdt_get_ddrhbb" [techpack/display/msm/msm_drm.ko] undefined!
ERROR: "of_fdt_get_ddrrank" [techpack/display/msm/msm_drm.ko] undefined!
ERROR: "of_fdt_get_ddrhbb" [drivers/gpu/msm/msm_adreno.ko] undefined!

Bug: 153905290
Bug: 151601060
Bug: 151568484
Test: compile
Change-Id: I3a20d333ed4b6450d3721d6ae191fc31be2033ed
Signed-off-by: lucaswei <lucaswei@google.com>
(cherry picked from commit b2c6888bdfbb768bdb40cdccd1a972548997e940)
Signed-off-by: Will McVicker <willmcvicker@google.com>