ANDROID: Ensure DIMLIB is available for kernel_virt_* builds
VIRTIO_NET depends on DIMLIB being built into the core kernel since it
is a bool.  However there is no way to know if a particular build is
going to attempt to build VIRTIO_NET as a module until after the fact.

Prevents the following pre-submit build failures:

  ERROR: modpost: "net_dim" [drivers/net/virtio_net.ko] undefined!
  ERROR: modpost: "net_dim_get_rx_moderation" [drivers/net/virtio_net.ko] undefined!

Fixes: 6208799553a8 ("virtio-net: support rx netdim")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ic99f0c475978ce04c58e3242c8fd4df2cc9a1a3c