ANDROID: fuse: fix kernelci break from mismatched ifdefs
fuse_dentry_init() and fuse_dentry_release() are defined when
BITS_PER_LONG < 64 or CONFIG_FUSE_BPF but only being used in
fuse_dentry_operations() when CONFIG_FUSE_BPF, resulting in the
following kernelci build errors on 32-bit arm:

with gcc-14:
/tmp/kci/linux/fs/fuse/dir.c:365:13: error: ‘fuse_dentry_release’ defined but not used [-Werror=unused-function]
  365 | static void fuse_dentry_release(struct dentry *dentry)
      |             ^~~~~~~~~~~~~~~~~~~
/tmp/kci/linux/fs/fuse/dir.c:358:12: error: ‘fuse_dentry_init’ defined but not used [-Werror=unused-function]
  358 | static int fuse_dentry_init(struct dentry *dentry)
      |            ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

with clang-21:
/tmp/kci/linux/fs/fuse/dir.c:358:12: error: unused function 'fuse_dentry_init' [-Werror,-Wunused-function]
  358 | static int fuse_dentry_init(struct dentry *dentry)
      |            ^~~~~~~~~~~~~~~~
/tmp/kci/linux/fs/fuse/dir.c:365:13: error: unused function 'fuse_dentry_release' [-Werror,-Wunused-function]
  365 | static void fuse_dentry_release(struct dentry *dentry)
      |             ^~~~~~~~~~~~~~~~~~~
2 errors generated.

The || defined(CONFIG_FUSE_BPF) was added to the definitions in commit
be926e6761d2  ("ANDROID: fuse-bpf: fuse-bpf v1.3") but the
BITS_PER_LONG < 64 in the struct definition was accidentally replaced in
the same commit. Restore the condition.

Fixes: be926e6761d2 ("ANDROID: fuse-bpf: fuse-bpf v1.3")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:e5623b54cd7b0dd2d724760c6a74bba0a0143df2
Closes: https://d.kernelci.org/i/maestro:e54589adc8d5c50be660a9b00292452a06e5f1b1
Change-Id: I07c0368cc8d2e8c1edaadc96ff436a29a2694d71
Signed-off-by: Tiffany Yang <ynaffit@google.com>