ANDROID: rust_binder: fix overflow in to_kernel_prio()
Userspace provides node priority values via flat_binder_object flags and
these might exceed the expected range for RT policies (0-99). This leads
to a subtraction overflow in to_kernel_prio():

  rust_kernel: panicked at drivers/android/binder/prio.rs:78:9:
  attempt to subtract with overflow
  ------------[ cut here ]------------
  kernel BUG at rust/helpers/bug.c:7!
  Oops: invalid opcode: 0000 [#1] PREEMPT SMP KASAN NOPTI

Let's make sure the calculation is safe from overflow by using
saturating_sub(). This caps invalid user input to zero which fails
validation at a later stage in do_set_priority().

Bug: 445669659
Suggested-by: Alice Ryhl <aliceryhl@google.com>
Fixes: c0d8982f50bc ("ANDROID: rust: add Task methods for priority inheritance")
Change-Id: I40831281d05cfd9a7efee2f249eb74e3d30ae4fd
Signed-off-by: Carlos Llamas <cmllamas@google.com>