ANDROID: KVM: arm64: iommu: Add missing CMA dependency
pKVM depends on CMA. When CONFIG_KVM=y but CONFIG_CMA is not selected,
kernelci builds fail with the following:

    aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
    aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_alloc':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:191:(.text+0x4f4): undefined reference to `cma_alloc'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_release':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:200:(.text+0x540): undefined reference to `cma_release'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_alloc':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:191:(.text+0x834): undefined reference to `cma_alloc'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_release':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:200:(.text+0xa04): undefined reference to `cma_release'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `pkvm_iommu_cma_setup':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:169:(.init.text+0x64): undefined reference to `cma_init_reserved_mem'
    aarch64-linux-gnu-ld: /tmp/kci/linux/arch/arm64/kvm/iommu.c:177:(.init.text+0x90): undefined reference to `cma_get_base'
    aarch64-linux-gnu-ld: /tmp/kci/linux/arch/arm64/kvm/iommu.c:178:(.init.text+0xa0): undefined reference to `cma_get_size'

Update the Kconfig dependency to ensure that the required symbols are
present.

Bug: 383901011
Bug: 277989609
Bug: 357781595
Fixes: c949df871d07 ("ANDROID: KVM: arm64: iommu: Allow donations from a
CMA pool")
Change-Id: I6d10d2c8e51ac414ee10b8b849a9f6dab8751948
Signed-off-by: Tiffany Yang <ynaffit@google.com>