ANDROID: x86: gki_defconfig: Start using CONFIG_BLK_DEV_INTEGRITY and CONFIG_DM_AUDIT
dm-integrity.ko module requires some additional symbols exported:
ERROR: modpost: "blk_integrity_register" [drivers/md/dm-integrity.ko] undefined!
ERROR: modpost: "dm_audit_log_bio" [drivers/md/dm-integrity.ko] undefined!
ERROR: modpost: "dm_audit_log_ti" [drivers/md/dm-integrity.ko] undefined!

Bug:355724960
Test: Check if there are mentioned build errors

Change-Id: Ib12a98fd6e3826b311469ce5069bd6e1e407a7ad
Signed-off-by: Tomasz Nowicki <tnowicki@google.com>