ANDROID: GKI: x86: update symbol list for desktop
11 function symbol(s) added
  'u64 ttm_backup_bytes_avail()'
  'void ttm_bo_lru_cursor_fini(struct ttm_bo_lru_cursor*)'
  'struct ttm_buffer_object* ttm_bo_lru_cursor_first(struct ttm_bo_lru_cursor*)'
  'struct ttm_bo_lru_cursor* ttm_bo_lru_cursor_init(struct ttm_bo_lru_cursor*, struct ttm_resource_manager*, struct ttm_operation_ctx*)'
  'struct ttm_buffer_object* ttm_bo_lru_cursor_next(struct ttm_bo_lru_cursor*)'
  'int ttm_bo_populate(struct ttm_buffer_object*, struct ttm_operation_ctx*)'
  'long ttm_bo_shrink(struct ttm_operation_ctx*, struct ttm_buffer_object*, struct ttm_bo_shrink_flags)'
  'bool ttm_bo_shrink_avoid_wait()'
  'bool ttm_bo_shrink_suitable(struct ttm_buffer_object*, struct ttm_operation_ctx*)'
  'int ttm_tt_restore(struct ttm_device*, struct ttm_tt*, const struct ttm_operation_ctx*)'
  'int ttm_tt_setup_backup(struct ttm_tt*)'

function symbol 'bool ttm_bo_eviction_valuable(struct ttm_buffer_object*, const struct ttm_place*)' changed
  CRC changed from 0x1943d007 to 0x98ce969a

function symbol 'int ttm_bo_init_reserved(struct ttm_device*, struct ttm_buffer_object*, enum ttm_bo_type, struct ttm_placement*, uint32_t, struct ttm_operation_ctx*, struct sg_table*, struct dma_resv*, void(*)(struct ttm_buffer_object*))' changed
  CRC changed from 0x90b204f2 to 0xc9bfa668

function symbol 'int ttm_bo_kmap(struct ttm_buffer_object*, unsigned long, unsigned long, struct ttm_bo_kmap_obj*)' changed
  CRC changed from 0x63cceaf9 to 0x70a7e7c9

... 36 omitted; 39 symbols have only CRC changes

type 'struct ttm_device' changed
  member 'struct list_head pinned' was removed
  member 'struct list_head unevictable' was added

type 'struct ttm_tt' changed
  byte size changed from 48 to 64
  member 'struct ttm_backup* backup' was added
  member 'enum ttm_caching caching' changed
    offset changed by 64
  member 'struct ttm_pool_tt_restore* restore' was added

INFO: Found 1 target...
Target //common:kernel_x86_64_abi_update up-to-date:
  bazel-bin/common/kernel_x86_64_abi_update.sh
INFO: Elapsed time: 258.119s, Critical Path: 253.92s
INFO: 22 processes: 1220 action cache hit, 5 internal, 13 linux-sandbox, 4 local.
INFO: Build completed successfully, 22 total actions
INFO: Running command line: bazel-bin/common/kernel_x86_64_abi_update.sh
ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

11 function symbol(s) added
  'u64 ttm_backup_bytes_avail()'
  'void ttm_bo_lru_cursor_fini(struct ttm_bo_lru_cursor*)'
  'struct ttm_buffer_object* ttm_bo_lru_cursor_first(struct ttm_bo_lru_cursor*)'
  'struct ttm_bo_lru_cursor* ttm_bo_lru_cursor_init(struct ttm_bo_lru_cursor*, struct ttm_resource_manager*, struct ttm_operation_ctx*)'
  'struct ttm_buffer_object* ttm_bo_lru_cursor_next(struct ttm_bo_lru_cursor*)'
  'int ttm_bo_populate(struct ttm_buffer_object*, struct ttm_operation_ctx*)'
  'long ttm_bo_shrink(struct ttm_operation_ctx*, struct ttm_buffer_object*, struct ttm_bo_shrink_flags)'
  'bool ttm_bo_shrink_avoid_wait()'
  'bool ttm_bo_shrink_suitable(struct ttm_buffer_object*, struct ttm_operation_ctx*)'
  'int ttm_tt_restore(struct ttm_device*, struct ttm_tt*, const struct ttm_operation_ctx*)'
  'int ttm_tt_setup_backup(struct ttm_tt*)'

function symbol 'bool ttm_bo_eviction_valuable(struct ttm_buffer_object*, const struct ttm_place*)' changed
  CRC changed from 0x1943d007 to 0x98ce969a

function symbol 'int ttm_bo_init_reserved(struct ttm_device*, struct ttm_buffer_object*, enum ttm_bo_type, struct ttm_placement*, uint32_t, struct ttm_operation_ctx*, struct sg_table*, struct dma_resv*, void(*)(struct ttm_buffer_object*))' changed
  CRC changed from 0x90b204f2 to 0xc9bfa668

function symbol 'int ttm_bo_kmap(struct ttm_buffer_object*, unsigned long, unsigned long, struct ttm_bo_kmap_obj*)' changed
  CRC changed from 0x63cceaf9 to 0x70a7e7c9

... 36 omitted; 39 symbols have only CRC changes

type 'struct ttm_device' changed
  member 'struct list_head pinned' was removed
  member 'struct list_head unevictable' was added

type 'struct ttm_tt' changed
  byte size changed from 48 to 64
  member 'struct ttm_backup* backup' was added
  member 'enum ttm_caching caching' changed
    offset changed by 64
  member 'struct ttm_pool_tt_restore* restore' was added

Bug: 417548663
Test: Builds and boots on PTL
Bypass-Upstream-Divergence-Tracking
Signed-off-by: Arselan Alvi <arselan.alvi@intel.com>
Change-Id: I4ca33d04d5d61b4467d1616e3442b3785c64e6dc
Signed-off-by:  Arselan Alvi <arselan.alvi@intel.corp-partner.google.com>