ANDROID: vendor_hooks: fix build error in blk-mq.c when vendor hooks are disabled
The commit f7f28e6be255 ("ANDROID: block: Introduce the
android_rvh_blk_mq_has_request() vendor hook") unconditionally exported
the android_rvh_blk_mq_has_request tracepoint in blk-mq.c.

However, when CONFIG_ANDROID_VENDOR_HOOKS is disabled (e.g., in Microdroid
builds), the DECLARE_RESTRICTED_HOOK macro in vendor_hooks.h expands to
DECLARE_EVENT_NOP, which does not define the __tracepoint_ structures.
This leads to the following compilation error:

error: use of undeclared identifier
	'__tracepoint_android_rvh_blk_mq_has_request';
did you mean 'trace_android_rvh_blk_mq_has_request'?
3573 | EXPORT_TRACEPOINT_SYMBOL_GPL(android_rvh_blk_mq_has_request);

Fix this by moving the export to drivers/android/vendor_hooks.c which
is the correct place and practice.

Fixes: f7f28e6be255ca ("ANDROID: block: Introduce the android_rvh_blk_mq_has_request() vendor hook")

Bug: 479780487
Change-Id: If3290b3e888700b1bc291627c2b2a55e19f0fff8
Signed-off-by: Sandeep Dhavale <dhavale@google.com>