ANDROID: lib/crypto: Select CRYPTO_LIB_UTILS with SHA256
The fips140 crypto function overrides rely on symbols that are defined
in utils.o. If CRYPTO_LIB_UTILS is not selected, kernelci builds fail
to link with the following errors:

with gcc-14:
ld: lib/crypto/sha256.o: in function `__hmac_sha256_init':
sha256.c:(.text+0x2): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x56): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `__sha256_update':
sha256.c:(.text+0x73): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x1c4): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256_finup_2x':
sha256.c:(.text+0x5c8): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x66c): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha224_init':
sha256.c:(.text+0x672): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x6b0): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256_init':
sha256.c:(.text+0x6c2): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x700): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256_finup_2x_is_optimized':
sha256.c:(.text+0x712): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x728): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha224_final':
sha256.c:(.text+0x732): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x775): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha224.part.0':
sha256.c:(.text+0x782): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256_final':
sha256.c:(.text+0x792): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x7d5): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256.part.0':
sha256.c:(.text+0x7e2): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224_final':
sha256.c:(.text+0x7f2): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x806): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224.part.0':
sha256.c:(.text+0x812): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224_usingrawkey.part.0':
sha256.c:(.text+0x822): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256_final':
sha256.c:(.text+0x832): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x846): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256.part.0':
sha256.c:(.text+0x852): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256_usingrawkey.part.0':
sha256.c:(.text+0x862): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha224':
sha256.c:(.text+0x880): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x89c): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x915): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `sha256':
sha256.c:(.text+0x930): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x94c): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0x9c5): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224_preparekey':
sha256.c:(.text+0xb32): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xb55): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256_preparekey':
sha256.c:(.text+0xb62): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xb85): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224_init_usingrawkey':
sha256.c:(.text+0xb92): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xbc4): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256_init_usingrawkey':
sha256.c:(.text+0xbd2): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xc04): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224_usingrawkey':
sha256.c:(.text+0xc2b): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xc45): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xc83): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xcc6): undefined reference to `fips140_lib_funcs'
ld: sha256.c:(.text+0xcd4): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256_usingrawkey':
sha256.c:(.text+0xcfb): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xd15): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xd53): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xd96): undefined reference to `fips140_lib_funcs'
ld: sha256.c:(.text+0xda4): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha256':
sha256.c:(.text+0xdc6): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xde6): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xe55): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xe95): undefined reference to `fips140_lib_funcs'
ld: sha256.c:(.text+0xea7): undefined reference to `fips140_lib_funcs'
ld: lib/crypto/sha256.o: in function `hmac_sha224':
sha256.c:(.text+0xec6): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xee6): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xf55): undefined reference to `fips140_lib_funcs_loaded'
ld: sha256.c:(.text+0xf95): undefined reference to `fips140_lib_funcs'
ld: sha256.c:(.text+0xfa7): undefined reference to `fips140_lib_funcs'
make[2]: *** [scripts/Makefile.vmlinux:72: vmlinux.unstripped] Error 1
make[1]: *** [/tmp/kci/linux/Makefile:1269: vmlinux] Error 2
make: *** [Makefile:266: __sub-make] Error 2

with clang-21:
ld.lld: error: undefined symbol: fips140_lib_funcs_loaded
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(sha224_init) in archive vmlinux.a
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(sha256_init) in archive vmlinux.a
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(__sha256_update) in archive vmlinux.a
>>> referenced 45 more times

ld.lld: error: undefined symbol: fips140_lib_funcs
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(sha224_init) in archive vmlinux.a
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(sha256_init) in archive vmlinux.a
>>> referenced by sha256.c
>>>               lib/crypto/sha256.o:(__sha256_update) in archive vmlinux.a
>>> referenced 35 more times
make[2]: *** [scripts/Makefile.vmlinux:72: vmlinux.unstripped] Error 1
make[1]: *** [/tmp/kci/linux/Makefile:1269: vmlinux] Error 2
make: *** [Makefile:266: __sub-make] Error 2

Fixes: 1aa0ebd06571 ("ANDROID: lib/crypto: Support overriding crypto library functions")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:f10a6458bd7dcc6badf9176d928a34be4852e29d
Closes: https://d.kernelci.org/i/maestro:f21e393cbecaf73c9d7c2cf74b604e258ec5759d
Closes: https://d.kernelci.org/i/maestro:b025469b8eee3797a745ac57ad38c07e0a658ffc
Change-Id: I0d8f264618b8c585b78bd99db1bfcdf39bcae4fa
Signed-off-by: Tiffany Yang <ynaffit@google.com>