Revert "tracefs: Have tracefs directories not set OTH permission bits by default"
This reverts commit 367fabbaf716de49972344028eb160c640ccc6ec. The change
breaks Android 10 userspace.

Before this patch, tracefs was accessible to non-root users:
  # ls -l /sys/kernel/debug/tracing
  ...
  drwxr-xr-x 76 root root 0 1969-12-31 16:00 events

After the patch, o+rx was removed from directories:
  # ls -l /sys/kernel/debug/tracing
  ...
  drwxr-x--- 76 root root 0 1969-12-31 16:00 events

which breaks Perfetto:
  $ ./record_android_trace -o trace_file.perfetto-trace -b 500mb \
        -a com.squareup sched freq idle am wm gfx view binder_driver hal \
        dalvik input res
  Running perfetto --background --txt [...]
  Trace started. Press CTRL+C to stop
  I/perfetto( 8117): probes_producer.cc:242 Ftrace setup (target_buf=402)
  E/perfetto( 8117): atrace_wrapper.cc:162 error: category "sched" is not
    supported on this device.
  E/perfetto( 8117): error enabling tracing category "sched"

On AOSP master, this was addressed with userspace patches to (1) add an
AID_READTRACEFS GID, (2) mount tracefs with gid=AID_READTRACEFS, and (3)
give shell and other processes this GID.[1]

It does not appear that these patches have been backported to Android 10
(or 11/12). Rather than backporting, it is more correct for LTS kernel
updates to not break userspace anyways.

[1]: https://android-review.googlesource.com/c/platform/system/core/+/1912638

Signed-off-by: Benjamin Li <benl@squareup.com>
Change-Id: I477b502ce31a6ba9920bf1ac2e625bbdc1c9d50b