Fix kernel build regressions from virtio-gpu-next patches
Fix the following:

drivers/gpu/drm/virtio/virtgpu_ioctl.c:587:8: warning: Variable 'buf' is
not assigned a value. [unassignedVariable]
drivers/gpu/drm/virtio/virtgpu_ioctl.c:624:9: warning: Local variable
'buf' shadows outer variable [shadowVariable]
drivers/gpu/drm/virtio/virtgpu_ioctl.c:678:50: warning: Either the
condition 'rc_blob->cmd_size&&vfpriv' is redundant or there is possible
null pointer dereference: vfpriv. [nullPointerRedundantCheck]
drivers/gpu/drm/virtio/virtgpu_ioctl.c:709:2: warning: 'buf' may be used
uninitialized in this function [-Wmaybe-uninitialized]
drivers/gpu/drm/virtio/virtgpu_kms.c:191:9: error: implicit declaration
of function 'pci_request_region'; did you mean 'pci_request_regions'?
[-Werror=implicit-function-declaration]

Bug: 155396530
Signed-off-by: Lingfeng Yang <lfy@google.com>
Change-Id: I10f4172cfa520b4cd80c3c7ec31996f1b6f2c298